/* patterns-data.js — the six Kubernetes tenancy models from the reference guide,
   plus the cross-cutting AI-Augmented Platform Operations layer.
   Exposes window.MODELS, window.THEMES, window.METERS, window.ADDONS,
   window.AI_ZONES, window.HEAL_STEPS. */

window.METERS = [
  { key: 'isolation',   label: 'Isolation',        icon: 'shield',      hint: 'How strongly tenants are kept apart',
    def: 'How strongly tenants are kept apart — security, resource & blast-radius boundaries. Higher = a noisy or compromised neighbour is less able to disrupt or reach the others.',
    lead: 'We rate the strength of the boundary between tenants — the harder it is for one tenant to see, reach, starve or crash another, the higher the score.',
    factors: [
      { dir: 'up',   text: 'Separate control planes or whole clusters per tenant — own API server, etcd & RBAC' },
      { dir: 'up',   text: 'Dedicated nodes or kernels, removing noisy-neighbour and shared-compute risk' },
      { dir: 'up',   text: 'Enforced NetworkPolicy, ResourceQuota & admission control at the boundary' },
      { dir: 'up',   text: 'A dedicated AWS account per tenant — separate IAM, service quotas & billing — the hardest boundary AWS offers' },
      { dir: 'down', text: 'Tenants sharing a namespace, where separation rests only on labels & convention' },
      { dir: 'down', text: 'A shared control plane, node pool or AWS account — one bad workload can reach the rest' },
    ] },
  { key: 'cost',        label: 'Cost efficiency',  icon: 'piggy-bank',  hint: 'Resource sharing & $ per tenant',
    def: 'Infrastructure spend per tenant. Higher = more nodes, control planes & add-ons are shared, so the cost of adding one more tenant is lower.',
    lead: 'We rate the marginal cost of one more tenant — the more compute, control planes and add-ons are shared, the cheaper each tenant becomes, the higher the score.',
    factors: [
      { dir: 'up',   text: 'Many tenants packed onto shared nodes behind a single control plane' },
      { dir: 'up',   text: 'One add-on stack (CNI, monitoring, security) amortised across every tenant' },
      { dir: 'down', text: 'A dedicated control plane — or a whole cluster — duplicated per tenant' },
      { dir: 'down', text: 'Idle headroom reserved per cell or cluster that cannot be pooled' },
    ] },
  { key: 'simplicity',  label: 'Ops simplicity',   icon: 'gauge',       hint: 'Day-2 effort to run it',
    def: 'Day-2 operational effort for the platform team. Higher = fewer moving parts, less toil to provision, patch, upgrade and observe.',
    lead: 'We rate the day-2 burden on the platform team — fewer distinct things to provision, patch, upgrade and observe means a higher score.',
    factors: [
      { dir: 'up',   text: 'A single (or few) cluster(s) and control plane(s) to run and upgrade' },
      { dir: 'up',   text: 'GitOps automation — declarative sync & drift control instead of manual toil' },
      { dir: 'down', text: 'Many clusters or cells multiplying the patch, upgrade & monitoring surface' },
      { dir: 'down', text: 'Extra abstraction layers (e.g. vcluster syncers) with their own failure modes' },
    ] },
  { key: 'scale',       label: 'Scalability',      icon: 'trending-up', hint: 'How far it stretches with the same team',
    def: 'How far the model stretches with the same team — adding tenants, regions or clusters without headcount growing in lock-step.',
    lead: 'We rate how far the model stretches as tenants, regions and clusters grow — without the platform team scaling in lock-step.',
    factors: [
      { dir: 'up',   text: 'Sharding by region / blast-zone so growth spreads across many clusters' },
      { dir: 'up',   text: 'GitOps + Cluster API automating fleet provisioning & tenant placement' },
      { dir: 'down', text: 'Per-cluster overhead that grows roughly linearly with tenant count' },
      { dir: 'down', text: 'A single shared cluster eventually hitting API-server / node-count limits' },
    ] },
];

/* How the 0–100 scores band into colors in the Compare matrix. */
window.SCORE_BANDS = [
  { band: 'lo',  range: '0–44',   label: 'Limited',  desc: 'a weak point of this model' },
  { band: 'mid', range: '45–74',  label: 'Moderate', desc: 'workable, with trade-offs' },
  { band: 'hi',  range: '75–100', label: 'Strong',   desc: 'a clear strength' },
];

/* Ordered shared → isolated (left → right on the spectrum). */
window.MODELS = [
  {
    id: 'isv',
    num: 1,
    name: 'ISV / Managed Service',
    tag: 'ISV / MSP PATTERN',
    tagline: 'Multi-customer, env-based namespaces, attribution via labels',
    icon: 'building-2',
    summary: 'A single owner operates the whole cluster and hosts apps for many customers. Namespaces are environment-scoped (prod, staging), so label conventions — customer=, tier=, app= — become the primary mechanism for alerting, routing and chargeback. The most shared model: many tenants share namespaces.',
    meters: { isolation: 32, cost: 96, simplicity: 82, scale: 78 },
    central: ['All infra: CNI, monitoring, security, CI/CD', 'Namespace structure (environments)', 'OPA/Kyverno: reject deploys missing labels', 'Alert routing & chargeback via label selectors'],
    tenant: ['Workloads tagged customer= tier= app=', 'Following the {customer}-{app}-{tier} convention', 'Sharing a namespace with other customers'],
    addonDelivery: 'Add-ons are owned entirely by the provider; label-based policy decides what each customer workload may do.',
    aiZone: 'autonomous',
    aiHook: 'Autonomous cost agents optimise spend per customer= label, with every action in the audit log.',
    aws: { model: '1 provider account', dataPlane: 'Managed node groups', boundary: 'shared',
      detail: 'Everything runs in one provider-owned AWS account. Customers share namespaces and are pulled apart by labels; chargeback rides on AWS Cost Categories keyed to customer=.' },
    diagram: 'isv',
  },
  {
    id: 'naas',
    num: 2,
    name: 'Multi-Tenant NaaS',
    tag: 'NAMESPACE AS A SERVICE',
    tagline: 'Shared cluster, team-scoped namespaces, centrally enforced isolation',
    icon: 'layers',
    summary: 'One shared cluster hosts many teams, each in its own namespace. The platform team runs all shared infrastructure — CNI, monitoring, security, logging — and provisions namespaces on request. Tenants operate strictly within those guardrails.',
    meters: { isolation: 56, cost: 92, simplicity: 80, scale: 80 },
    central: ['CNI layer (VPC CNI / Cilium)', 'Monitoring (Prometheus / Grafana)', 'Security agents & admission (Falco, OPA/Kyverno)', 'Logging (Fluentd / Loki)', 'RBAC, NetworkPolicy & namespace provisioning'],
    tenant: ['Workloads within their namespace', 'Responding to alerts routed to them', 'Cannot exceed their ResourceQuota'],
    addonDelivery: 'One shared add-on stack serves every tenant namespace — enforced cluster-wide, tenants cannot override.',
    aiZone: 'declarative',
    aiHook: 'Declarative agents handle namespace-provisioning requests through GitOps pull requests.',
    aws: { model: '1 platform account', dataPlane: 'Managed node groups', boundary: 'shared',
      detail: 'A single platform AWS account runs one shared EKS cluster. IAM roles map to team RBAC via EKS access entries; IRSA scopes each namespace to its own AWS permissions.' },
    diagram: 'naas',
  },
  {
    id: 'vcluster',
    num: 3,
    name: 'Virtual Clusters',
    tag: 'VCLUSTER',
    tagline: 'A full cluster experience per tenant, inside a shared physical one',
    icon: 'box',
    summary: 'Each tenant gets what feels like a dedicated cluster — its own API server, control-plane view and CRDs — but it runs inside a namespace on a shared host cluster. Nodes, networking and storage are shared; the control plane is not.',
    meters: { isolation: 74, cost: 80, simplicity: 60, scale: 80 },
    central: ['Physical nodes, CNI & storage classes', 'Host-level security agents & monitoring', 'Host-namespace resource quotas', 'vCluster lifecycle (provision, upgrade)'],
    tenant: ['Their own virtual API server & etcd', 'Full RBAC & CRDs inside the vcluster', 'Cluster-level control without a real cluster'],
    addonDelivery: 'Host add-ons are shared; each vcluster can install its own add-ons independently inside its virtual control plane.',
    aiZone: 'assisted',
    aiZoneTo: 'declarative',
    aiHook: 'AI advises on host capacity & syncer health, then spins up ephemeral vclusters on request.',
    aws: { model: '1 host account', dataPlane: 'Shared managed node groups', boundary: 'shared',
      detail: 'vclusters are logical — they still live in one host AWS account. Each tenant gets its own virtual API server, but IAM, VPC and quotas remain host-account-scoped (the key caveat).' },
    diagram: 'vcluster',
  },
  {
    id: 'gitops',
    num: 4,
    name: 'Regional / Sharded Fleet',
    tag: 'FLEET · REGION-SHARDED',
    tagline: 'A few multi-tenant clusters, sharded by region / blast-zone, GitOps-managed',
    icon: 'git-branch',
    summary: 'Instead of one shared cluster, tenants are spread across a handful of real clusters — each a regional or blast-zone shard that still hosts many tenants. Git is the source of truth: Cluster API provisions the shards and ArgoCD / Flux continuously sync add-ons, policy and apps to all of them. A fault is contained to one region, not the whole platform — but a shard is still shared, not per-customer.',
    meters: { isolation: 82, cost: 50, simplicity: 90, scale: 95 },
    central: ['Git as source of truth (clusters/ addons/ policies/)', 'Cluster API provisions regional shards', 'ArgoCD / Flux continuous sync & drift control', 'Tenant → shard placement (by region / tier)'],
    tenant: ['Workloads delivered via pull request', 'Share a regional shard with other tenants', 'Fault contained to their region, not the platform'],
    addonDelivery: 'Add-ons live in Git and are declaratively synced to every shard cluster — drift is auto-reconciled, never manual.',
    aiZone: 'declarative',
    aiZoneTo: 'autonomous',
    aiHook: 'The natural home for declarative agents — drift remediation runs across the fleet without per-action approval.',
    aws: { model: 'A few accounts · 1 per region + mgmt', dataPlane: 'Managed node groups per shard', boundary: 'per-region',
      detail: 'A management account holds Git, Cluster API & ArgoCD; each regional shard is its own workload account with its own VPC. Cross-account IAM lets the hub reconcile every shard.' },
    diagram: 'gitops',
  },
  {
    id: 'cell',
    num: 5,
    name: 'Cell-Based Architecture',
    tag: 'CELL-BASED',
    tagline: 'Per-customer cluster shards — hard blast-radius isolation',
    icon: 'grid-3x3',
    summary: 'Customers are sharded across isolated infrastructure cells — a dedicated cluster or node pool per customer (or small group). A management-only hub cluster provisions and syncs every cell via GitOps, while customer → cell routing is handled by a global LB / DNS layer outside Kubernetes — so a noisy or failing customer (or hub) can never take another down.',
    meters: { isolation: 92, cost: 42, simplicity: 58, scale: 94 },
    central: ['Hub / management cluster (Cluster API + ArgoCD)', 'Cell provisioning & sync via GitOps', 'Global LB / DNS routing (outside K8s)', 'Shared observability, security & policy'],
    tenant: ['An isolated cluster or node pool', 'Independent scale — no noisy neighbour', 'Failure contained to their own cell'],
    addonDelivery: 'A shared baseline of add-ons is pushed from the hub to every cell, then each cell runs them independently.',
    aiZone: 'declarative',
    aiZoneTo: 'autonomous',
    aiHook: 'Agents trigger cell provisioning via Git and autonomously scale each cell per tenant.',
    aws: { model: 'Account per cell + hub account', dataPlane: 'Dedicated node groups per cell', boundary: 'per-cell',
      detail: 'A hub account runs Cluster API + ArgoCD and vends each cell into its own AWS account (Account Factory). Global routing lives in a separate account — a failing cell can’t reach the others.' },
    diagram: 'cell',
  },
  {
    id: 'single',
    num: 6,
    name: 'Single-Tenant Clusters',
    tag: 'DEDICATED CLUSTERS',
    tagline: 'One dedicated cluster per team — the strongest isolation',
    icon: 'server',
    summary: 'A central platform team owns the full cluster lifecycle — provisioning, patching, upgrades, security tooling — and hands each app team its own dedicated cluster. The strongest isolation Kubernetes offers, with cost and overhead that scale linearly with cluster count.',
    meters: { isolation: 98, cost: 36, simplicity: 40, scale: 58 },
    central: ['Cluster provisioning & lifecycle', 'Add-ons: ingress, cert-manager, external-dns', 'Security agents: Falco, audit logging', 'Alerting pipelines → routed to app owner'],
    tenant: ['All deployments, services & config', 'Responding to surfaced alerts', 'App scaling & rollout decisions'],
    addonDelivery: 'A full add-on stack is installed and centrally managed inside every dedicated cluster.',
    aiZone: 'assisted',
    aiHook: 'AI advises on cluster upgrades and patch windows — a human approves each action.',
    aws: { model: 'Account per team', dataPlane: 'Dedicated node groups per cluster', boundary: 'per-tenant',
      detail: 'Every team gets its own AWS account with a dedicated EKS cluster — separate IAM, KMS, VPC, quotas and bill. The strongest boundary AWS offers, at a cost that grows linearly.' },
    diagram: 'single',
  },
];

/* Amazon EKS add-on stack — the shared services the platform account manages. */
window.ADDONS = [
  { name: 'Amazon VPC CNI',           icon: 'network',      role: 'Networking' },
  { name: 'CoreDNS',                  icon: 'globe',        role: 'DNS' },
  { name: 'kube-proxy',               icon: 'route',        role: 'Networking' },
  { name: 'AWS Load Balancer Ctrl',   icon: 'route',        role: 'Ingress' },
  { name: 'Karpenter',                icon: 'maximize-2',   role: 'Autoscaling' },
  { name: 'EBS / EFS CSI',            icon: 'database',     role: 'Storage' },
  { name: 'ExternalDNS → Route 53',   icon: 'globe',        role: 'DNS' },
  { name: 'IRSA / Pod Identity',      icon: 'shield-check', role: 'Identity' },
  { name: 'GuardDuty (EKS)',          icon: 'shield',       role: 'Security' },
  { name: 'Container Insights',       icon: 'activity',     role: 'Monitoring' },
  { name: 'ArgoCD / Flux',            icon: 'git-branch',   role: 'GitOps' },
];

/* AI-Augmented Platform Operations — the autonomy spectrum (Model 7). */
window.AI_ZONES = [
  {
    id: 'assisted',
    num: 1,
    accent: 'var(--t5)',
    label: 'AI-Assisted',
    sub: 'Human decides, AI advises',
    icon: 'eye',
    desc: 'Agents surface information and suggestions. Engineers keep full control — the agent never writes to the cluster without explicit approval.',
    guardrail: 'Human approval required for every action',
    tools: [
      { name: 'K8sGPT', desc: 'Plain-English diagnostics for errors, misconfigs and events' },
      { name: 'Botkube AI', desc: 'Investigates alerts in Slack/Teams, suggests kubectl to run' },
      { name: 'kubectl-ai', desc: 'Turns natural-language intent into reviewable kubectl commands' },
      { name: 'Lens Prism', desc: 'AI insights embedded inline in the Kubernetes IDE' },
    ],
    applies: ['Every model benefits — the lowest-risk entry point', 'Model 6 Single-Tenant — upgrade & patch advice', 'Model 3 vCluster — host capacity & syncer health'],
  },
  {
    id: 'declarative',
    num: 2,
    accent: 'var(--t1)',
    label: 'Declarative Agents',
    sub: 'Agents as Kubernetes resources',
    icon: 'git-pull-request',
    desc: 'Agents are defined as manifests and managed like any other K8s resource — GitOps, RBAC, admission control and audit trails. They operate within the declarative model, not around it.',
    guardrail: 'GitOps PR workflow + RBAC + admission control',
    tools: [
      { name: 'kagent (CNCF)', desc: 'Agents as CRDs on MCP — managed via kubectl & GitOps' },
      { name: 'Agent Sandbox', desc: 'Upstream CRD for isolated, long-running agent runtimes' },
      { name: 'Akuity AI', desc: 'Every action tracked via the ArgoCD audit trail' },
      { name: 'Crossplane + AI', desc: 'AI drafts compositions; GitOps applies them' },
    ],
    applies: ['Model 4 Sharded Fleet — the natural home', 'Model 2 NaaS — agents handle NS provisioning', 'Model 5 Cell-Based — agents trigger cell provisioning'],
  },
  {
    id: 'autonomous',
    num: 3,
    accent: 'var(--t6)',
    label: 'Autonomous Ops',
    sub: 'Scoped autonomy + audit trails',
    icon: 'zap',
    desc: 'Agents act without per-action approval, but inside tightly scoped domains with full auditability — cost, deploy verification, incident response — where the blast radius of a wrong action is bounded.',
    guardrail: 'Scoped RBAC + full audit trail + bounded blast radius',
    tools: [
      { name: 'Metoro', desc: 'Compares pre/post-deploy telemetry, auto-verifies releases' },
      { name: 'Cast AI', desc: 'Real-time autonomous cost & compute optimisation' },
      { name: 'Akuity (full)', desc: 'End-to-end incident triage; all actions logged' },
      { name: 'KEDA + LangGraph', desc: 'Event-driven autoscaling of agent workloads to zero' },
    ],
    applies: ['Model 1 ISV/MSP — cost agents per customer=', 'Model 5 Cell-Based — autonomous cell scaling', 'Model 4 Sharded Fleet — drift remediation without a human'],
  },
];

/* Scripted self-healing scenario for the AI Ops demo (a Zone-3, audit-trailed example). */
window.HEAL_STEPS = [
  { tag: 'MONITOR',   text: 'Monitoring · all systems nominal · SLO 99.95%',           tone: 'ok' },
  { tag: 'ANOMALY',   text: 'Anomaly detected · 2 pods CrashLoopBackOff on node-2',     tone: 'bad' },
  { tag: 'DIAGNOSE',  text: 'Root cause · node-2 disk pressure is evicting the kubelet', tone: 'warn' },
  { tag: 'REMEDIATE', text: 'Action · cordon node-2 · reschedule pods → node-1',         tone: 'act' },
  { tag: 'RECOVERED', text: 'Recovered in 38s · SLO preserved · action written to audit log', tone: 'ok' },
];

/* Theme metadata for the in-page switcher. Colors live in CSS [data-theme]. */
window.THEMES = [
  { id: 'prism',     name: 'Prism',     blurb: 'Bright rainbow',  icon: 'palette',  swatch: ['#ff5d73','#f4c430','#37c97a','#2bb8c9','#6a7bff'] },
  { id: 'aurora',    name: 'Aurora',    blurb: 'Neon midnight',   icon: 'sparkles', swatch: ['#ff5e87','#ffe24a','#46f08a','#34e0e8','#6f8cff'] },
  { id: 'blueprint', name: 'Blueprint', blurb: 'Technical draft', icon: 'ruler',    swatch: ['#39c2d7','#f0a73c','#e2657a','#5bbf86','#6f8cd9'] },
];
